apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper1
  namespace: zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper1
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      containers:
      - name: zookeeper1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2
        volumeMounts:
        - mountPath: /var/kafka
          name: zoo-file
      volumes:
      - name: zoo-file
        persistentVolumeClaim:
          claimName: zoo-file      
