kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zoo-file
  namespace: zoo
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0754
  - file_mode=0754
  - uid=1534
  - gid=2546
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zoo1-file
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: zoo1-file
  resources:
    requests:
      storage: 1Gi
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper1
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      containers:
      - name: zookeeper1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2
        volumeMounts:
        - mountPath: /var/zoo
          name: zoo1-file
      volumes:
      - name: zoo1-file
        persistentVolumeClaim:
          claimName: zoo1-file      
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: zookeeper2
spec:
  replicas: 1
  selector:
    matchLabels:      
      app: zookeeper2
  template:
    metadata:
      labels:
        app: zookeeper2
    spec:
      containers:
      - name: zookeeper2
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2
        volumeMounts:
        - mountPath: /var/zoo
          name: zoo1-file
      volumes:
      - name: zoo1-file
        persistentVolumeClaim:
          claimName: zoo1-file
---
kind: Service
apiVersion: v1
metadata:
  name: zoo1
spec:
  type: LoadBalancer
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
  selector:
    app: zookeeper1

---
kind: Service
apiVersion: v1
metadata:
  name: zoo2
spec:
  type: LoadBalancer
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
  selector:
    app: zookeeper2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:      
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.240.0.5
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
        volumeMounts:
        - mountPath: /var/kafka
          name: zoo1-file
        volumes:
        - name: zoo1-file
          persistentVolumeClaim:
            claimName: zoo1-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:      
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.240.0.4
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
        volumeMounts: 
        - mountPath: /var/kafka
          name: zoo1-file
      volumes:
      - name: zoo1-file
        persistentVolumeClaim:
          claimName: zoo1-file
---
apiVersion: v1
kind: Service
metadata:     
  name: kaf1
spec:
  type: LoadBalancer
  externalIPs:
    - 10.240.0.5
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
spec:
  type: LoadBalancer
  externalIPs:
    - 10.240.0.4
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka2

  
